// Email Service using EmailJS
// Setup instructions at the bottom of this file

import emailjs from '@emailjs/browser';
import { generateResultsPDF } from './pdfGenerator';

// ============================================
// EMAILJS CONFIGURATION
// Replace these with your EmailJS credentials after setup
// ============================================
const EMAILJS_SERVICE_ID = 'service_4ijwema';
const EMAILJS_TEMPLATE_ID = 'template_r4h8m4m';
const EMAILJS_PUBLIC_KEY = 'dAyW9hMJ5rWhRXXFo';

/**
 * Check if EmailJS is configured
 */
export function isEmailConfigured() {
  return EMAILJS_SERVICE_ID !== 'YOUR_SERVICE_ID' &&
         EMAILJS_TEMPLATE_ID !== 'YOUR_TEMPLATE_ID' &&
         EMAILJS_PUBLIC_KEY !== 'YOUR_PUBLIC_KEY';
}

/**
 * Send results PDF via email
 */
export async function sendResultsEmail(studentInfo, scores, answers, questions, practiceType = null) {
  if (!isEmailConfigured()) {
    console.log('EmailJS not configured. Opening mailto instead.');
    return { success: false, reason: 'not_configured' };
  }

  if (!studentInfo.email) {
    return { success: false, reason: 'no_email' };
  }

  try {
    // Generate PDF
    const doc = generateResultsPDF(studentInfo, scores, answers, questions, practiceType);
    const pdfBase64 = doc.output('datauristring').split(',')[1]; // Remove data:application/pdf;base64, prefix

    // Calculate scores for email content
    const isFullTest = !practiceType;
    let totalCorrect, totalQuestions;
    if (isFullTest) {
      totalCorrect = (scores.rw1 || 0) + (scores.rw2 || 0) + (scores.math1 || 0) + (scores.math2 || 0);
      totalQuestions = 98;
    } else {
      totalCorrect = practiceType === 'readingWriting'
        ? (scores.rw1 || 0) + (scores.rw2 || 0)
        : (scores.math1 || 0) + (scores.math2 || 0);
      totalQuestions = questions.length;
    }
    const percentage = Math.round((totalCorrect / totalQuestions) * 100);

    const testType = isFullTest ? 'Full Practice Test' :
      (practiceType === 'readingWriting' ? 'Reading & Writing Practice' : 'Math Practice');

    // Send email via EmailJS
    const templateParams = {
      to_email: studentInfo.email,
      to_name: studentInfo.name || 'Student',
      student_name: studentInfo.name || 'Anonymous',
      test_type: testType,
      total_correct: totalCorrect,
      total_questions: totalQuestions,
      percentage: percentage,
      date: new Date().toLocaleDateString('en-US', {
        weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
      }),
      pdf_attachment: pdfBase64,
    };

    const response = await emailjs.send(
      EMAILJS_SERVICE_ID,
      EMAILJS_TEMPLATE_ID,
      templateParams,
      EMAILJS_PUBLIC_KEY
    );

    console.log('Email sent successfully:', response);
    return { success: true, response };

  } catch (error) {
    console.error('Failed to send email:', error);
    return { success: false, error: error.message };
  }
}

/**
 * Fallback: Open mailto with basic info (no attachment)
 */
export function openMailtoFallback(studentInfo, scores, answers, questions, practiceType = null) {
  const isFullTest = !practiceType;
  let totalCorrect, totalQuestions;
  if (isFullTest) {
    totalCorrect = (scores.rw1 || 0) + (scores.rw2 || 0) + (scores.math1 || 0) + (scores.math2 || 0);
    totalQuestions = 98;
  } else {
    totalCorrect = practiceType === 'readingWriting'
      ? (scores.rw1 || 0) + (scores.rw2 || 0)
      : (scores.math1 || 0) + (scores.math2 || 0);
    totalQuestions = questions.length;
  }
  const percentage = Math.round((totalCorrect / totalQuestions) * 100);
  const testType = isFullTest ? 'Full Practice Test' :
    (practiceType === 'readingWriting' ? 'R/W Practice' : 'Math Practice');

  const subject = encodeURIComponent(`SAT Practice Results - ${percentage}% (${testType})`);

  let body = `SAT Practice Test Results
========================

Student: ${studentInfo.name || 'Anonymous'}
Date: ${new Date().toLocaleDateString()}
Test Type: ${testType}

OVERALL SCORE: ${totalCorrect}/${totalQuestions} (${percentage}%)

MODULE BREAKDOWN:
`;

  if (isFullTest || practiceType === 'readingWriting') {
    body += `- R/W Module 1: ${scores.rw1 || 0}/27
- R/W Module 2: ${scores.rw2 || 0}/27
`;
  }

  if (isFullTest || practiceType === 'math') {
    body += `- Math Module 1: ${scores.math1 || 0}/22
- Math Module 2: ${scores.math2 || 0}/22
`;
  }

  body += '\n--\nGenerated by SAT Practice App\n\nNote: Please download the PDF from the results page for the full detailed report.';

  const encodedBody = encodeURIComponent(body);
  const mailtoLink = `mailto:${studentInfo.email || ''}?subject=${subject}&body=${encodedBody}`;

  window.location.href = mailtoLink;
}

/*
============================================
EMAILJS SETUP INSTRUCTIONS
============================================

To enable direct email sending with PDF attachments:

1. CREATE EMAILJS ACCOUNT
   - Go to https://www.emailjs.com/
   - Sign up for a free account (200 emails/month free)

2. ADD EMAIL SERVICE
   - Go to "Email Services" in dashboard
   - Click "Add New Service"
   - Choose your email provider (Gmail, Outlook, etc.)
   - Follow the connection steps
   - Copy the SERVICE ID (e.g., "service_abc123")

3. CREATE EMAIL TEMPLATE
   - Go to "Email Templates"
   - Click "Create New Template"
   - Design your template with these variables:

   Subject: SAT Practice Results - {{student_name}}

   Body:
   ---
   Hi {{to_name}},

   Here are your SAT Practice Test results from {{date}}.

   Test Type: {{test_type}}
   Score: {{total_correct}}/{{total_questions}} ({{percentage}}%)

   Your detailed results PDF is attached.

   Best of luck with your SAT preparation!
   ---

   - For the PDF attachment, add an attachment field with variable: {{pdf_attachment}}
   - Copy the TEMPLATE ID (e.g., "template_xyz789")

4. GET PUBLIC KEY
   - Go to "Account" > "General"
   - Copy your PUBLIC KEY

5. UPDATE THIS FILE
   - Replace the three constants at the top:
     EMAILJS_SERVICE_ID = 'service_abc123';
     EMAILJS_TEMPLATE_ID = 'template_xyz789';
     EMAILJS_PUBLIC_KEY = 'your_public_key';

6. TEST
   - Rebuild: npm run build
   - Take a practice test
   - Click "Email Results"
   - Check your inbox!

Note: The free tier allows 200 emails/month. For higher volume,
consider upgrading or using an alternative like SendGrid.

============================================
*/
